name: Merge PR

on:
  pull_request:
    types: [closed]

jobs:
  say_pr_merged:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "Pull Request mergée !"
