name: Workflow Suivant

on:
  workflow_run:
    workflows: ["Merge PR"]
    types:
      - completed

jobs:
  next_job:
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "Workflow Suivant exécuté après Merge PR ✅"
