name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create source file
        run: |
          mkdir -p src
          echo "console.log('Hello from Node.js CI workflow!');" > src/index.js

      - name: Build project
        run: |
          mkdir -p dist
          cp src/index.js dist/index.js
          echo "Build completed!"

      - name: Run script
        run: node dist/index.js
